# Generated by Django 5.0.4 on 2024-04-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('duration', models.TextField()),
                ('imageUrl', models.TextField()),
            ],
        ),
    ]
